/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab5p2_luismontalvan;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author luism
 */
public class Lab5P2_LuisMontalvan extends javax.swing.JFrame {
    
    /**
     * Creates new form Lab5P2_LuisMontalvan
     */
    public Lab5P2_LuisMontalvan() {
        initComponents();
        jPAgregarPersonaje.setVisible(false);
        jPListado.setVisible(false);
        jPSimulacion.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBG = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jBtnAgregar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPVacio = new javax.swing.JPanel();
        jPAgregarPersonaje = new javax.swing.JPanel();
        jTFNombre = new javax.swing.JTextField();
        jLTitulo = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLUniverso = new javax.swing.JLabel();
        jCBUniverso = new javax.swing.JComboBox<>();
        jLPoder = new javax.swing.JLabel();
        jTFPoder = new javax.swing.JTextField();
        jLFuerza = new javax.swing.JLabel();
        jTFFuerza = new javax.swing.JTextField();
        jLAFisica = new javax.swing.JLabel();
        jTFAFisica = new javax.swing.JTextField();
        jLAMental = new javax.swing.JLabel();
        jTFAMental = new javax.swing.JTextField();
        jLPuntosVida = new javax.swing.JLabel();
        jTFPuntosVida = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPListado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTPersonajes = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPSimulacion = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);

        jBtnAgregar.setText("Agregar Personaje");
        jBtnAgregar.setFocusable(false);
        jBtnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAgregarMouseClicked(evt);
            }
        });
        jBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnAgregar);

        jButton2.setText("Lisatdo de Personajes");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setText("Simulacion de Batalla");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jPBG.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 25));

        javax.swing.GroupLayout jPVacioLayout = new javax.swing.GroupLayout(jPVacio);
        jPVacio.setLayout(jPVacioLayout);
        jPVacioLayout.setHorizontalGroup(
            jPVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPVacioLayout.setVerticalGroup(
            jPVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPBG.add(jPVacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 600, 480));

        jLTitulo.setText("Agregar Personaje");

        jLNombre.setText("Nombre");

        jLUniverso.setText("Universo");

        jCBUniverso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DC", "Marvel", "Capcom", "Mortal Kombat" }));
        jCBUniverso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBUniversoActionPerformed(evt);
            }
        });

        jLPoder.setText("Poder");

        jTFPoder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPoderActionPerformed(evt);
            }
        });

        jLFuerza.setText("Fuerza");

        jTFFuerza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFFuerzaActionPerformed(evt);
            }
        });

        jLAFisica.setText("Agilidad Fisica");

        jTFAFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAFisicaActionPerformed(evt);
            }
        });

        jLAMental.setText("Agilidad Mental");

        jTFAMental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAMentalActionPerformed(evt);
            }
        });

        jLPuntosVida.setText("Puntos de Vida");

        jButton1.setText("Agregar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPAgregarPersonajeLayout = new javax.swing.GroupLayout(jPAgregarPersonaje);
        jPAgregarPersonaje.setLayout(jPAgregarPersonajeLayout);
        jPAgregarPersonajeLayout.setHorizontalGroup(
            jPAgregarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAgregarPersonajeLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPAgregarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLPoder, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLUniverso)
                    .addComponent(jLTitulo)
                    .addComponent(jLNombre)
                    .addComponent(jTFNombre)
                    .addComponent(jLFuerza)
                    .addComponent(jLAFisica)
                    .addGroup(jPAgregarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLPuntosVida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLAMental, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jTFPoder)
                    .addComponent(jTFFuerza)
                    .addComponent(jTFAFisica)
                    .addComponent(jTFAMental)
                    .addComponent(jTFPuntosVida)
                    .addComponent(jCBUniverso, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPAgregarPersonajeLayout.setVerticalGroup(
            jPAgregarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAgregarPersonajeLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLTitulo)
                .addGap(18, 18, 18)
                .addComponent(jLNombre)
                .addGap(5, 5, 5)
                .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLUniverso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBUniverso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLPoder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFPoder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPAgregarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPAgregarPersonajeLayout.createSequentialGroup()
                        .addComponent(jLFuerza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLAFisica))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFAFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLAMental)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFAMental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLPuntosVida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFPuntosVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jPBG.add(jPAgregarPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane1.setViewportView(jTPersonajes);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPListadoLayout = new javax.swing.GroupLayout(jPListado);
        jPListado.setLayout(jPListadoLayout);
        jPListadoLayout.setHorizontalGroup(
            jPListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPListadoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        jPListadoLayout.setVerticalGroup(
            jPListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPListadoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jPBG.add(jPListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPSimulacionLayout = new javax.swing.GroupLayout(jPSimulacion);
        jPSimulacion.setLayout(jPSimulacionLayout);
        jPSimulacionLayout.setHorizontalGroup(
            jPSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPSimulacionLayout.setVerticalGroup(
            jPSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPBG.add(jPSimulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAgregarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCBUniversoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBUniversoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBUniversoActionPerformed

    private void jTFPoderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPoderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPoderActionPerformed

    private void jTFFuerzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFFuerzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFFuerzaActionPerformed

    private void jTFAFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFAFisicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFAFisicaActionPerformed

    private void jTFAMentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFAMentalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFAMentalActionPerformed

    private void jBtnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAgregarMouseClicked
            // TODO add your handling code here:
            jPVacio.setVisible(false);
            jPAgregarPersonaje.setVisible(true);
    }//GEN-LAST:event_jBtnAgregarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        JOptionPane.showMessageDialog(this, "Agregado con exito");
        DefaultTreeModel modelo = (DefaultTreeModel)jTPersonajes.getModel();
        
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab5P2_LuisMontalvan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab5P2_LuisMontalvan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab5P2_LuisMontalvan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab5P2_LuisMontalvan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab5P2_LuisMontalvan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jCBUniverso;
    private javax.swing.JLabel jLAFisica;
    private javax.swing.JLabel jLAMental;
    private javax.swing.JLabel jLFuerza;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLPoder;
    private javax.swing.JLabel jLPuntosVida;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLUniverso;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPAgregarPersonaje;
    private javax.swing.JPanel jPBG;
    private javax.swing.JPanel jPListado;
    private javax.swing.JPanel jPSimulacion;
    private javax.swing.JPanel jPVacio;
    private javax.swing.JPanel jPVacio1;
    private javax.swing.JPanel jPVacio2;
    private javax.swing.JPanel jPVacio3;
    private javax.swing.JPanel jPVacio4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFAFisica;
    private javax.swing.JTextField jTFAMental;
    private javax.swing.JTextField jTFFuerza;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFPoder;
    private javax.swing.JTextField jTFPuntosVida;
    private javax.swing.JTree jTPersonajes;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    ArrayList<Personaje> personajes = new ArrayList();
}
