/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab5p2_luismontalvan;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author luism
 */
public class Lab5P2_LuisMontalvan extends javax.swing.JFrame {
    
    /**
     * Creates new form Lab5P2_LuisMontalvan
     */
    public Lab5P2_LuisMontalvan() {
        initComponents();
        jPAgregarPersonaje.setVisible(false);
        jPListado.setVisible(false);
        jPSimulacion.setVisible(false);
        jTFName.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBG = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jBtnAgregar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPVacio = new javax.swing.JPanel();
        jPAgregarPersonaje = new javax.swing.JPanel();
        jTFNombre = new javax.swing.JTextField();
        jLTitulo = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLUniverso = new javax.swing.JLabel();
        jCBUniverso = new javax.swing.JComboBox<>();
        jLPoder = new javax.swing.JLabel();
        jTFPoder = new javax.swing.JTextField();
        jLFuerza = new javax.swing.JLabel();
        jTFFuerza = new javax.swing.JTextField();
        jLAFisica = new javax.swing.JLabel();
        jTFAFisica = new javax.swing.JTextField();
        jLAMental = new javax.swing.JLabel();
        jTFAMental = new javax.swing.JTextField();
        jLPuntosVida = new javax.swing.JLabel();
        jTFPuntosVida = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPListado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTPersonajes = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        jTFName = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTPPersonajeInfo = new javax.swing.JTextPane();
        jPSimulacion = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);

        jBtnAgregar.setText("Agregar Personaje");
        jBtnAgregar.setFocusable(false);
        jBtnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAgregarMouseClicked(evt);
            }
        });
        jBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnAgregar);

        jButton2.setText("Lisatdo de Personajes");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setText("Simulacion de Batalla");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jPBG.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 25));

        javax.swing.GroupLayout jPVacioLayout = new javax.swing.GroupLayout(jPVacio);
        jPVacio.setLayout(jPVacioLayout);
        jPVacioLayout.setHorizontalGroup(
            jPVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPVacioLayout.setVerticalGroup(
            jPVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPBG.add(jPVacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 600, 480));

        jLTitulo.setText("Agregar Personaje");

        jLNombre.setText("Nombre");

        jLUniverso.setText("Universo");

        jCBUniverso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DC", "Marvel", "Capcom", "Mortal Kombat" }));
        jCBUniverso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBUniversoActionPerformed(evt);
            }
        });

        jLPoder.setText("Poder");

        jTFPoder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPoderActionPerformed(evt);
            }
        });

        jLFuerza.setText("Fuerza");

        jTFFuerza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFFuerzaActionPerformed(evt);
            }
        });

        jLAFisica.setText("Agilidad Fisica");

        jTFAFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAFisicaActionPerformed(evt);
            }
        });

        jLAMental.setText("Agilidad Mental");

        jTFAMental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAMentalActionPerformed(evt);
            }
        });

        jLPuntosVida.setText("Puntos de Vida");

        jButton1.setText("Agregar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPAgregarPersonajeLayout = new javax.swing.GroupLayout(jPAgregarPersonaje);
        jPAgregarPersonaje.setLayout(jPAgregarPersonajeLayout);
        jPAgregarPersonajeLayout.setHorizontalGroup(
            jPAgregarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAgregarPersonajeLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPAgregarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLPoder, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLUniverso)
                    .addComponent(jLTitulo)
                    .addComponent(jLNombre)
                    .addComponent(jTFNombre)
                    .addComponent(jLFuerza)
                    .addComponent(jLAFisica)
                    .addComponent(jLPuntosVida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLAMental)
                    .addComponent(jTFPoder)
                    .addComponent(jTFFuerza)
                    .addComponent(jTFAFisica)
                    .addComponent(jTFAMental)
                    .addComponent(jTFPuntosVida)
                    .addComponent(jCBUniverso, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPAgregarPersonajeLayout.setVerticalGroup(
            jPAgregarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAgregarPersonajeLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLTitulo)
                .addGap(18, 18, 18)
                .addComponent(jLNombre)
                .addGap(5, 5, 5)
                .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLUniverso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBUniverso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLPoder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFPoder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPAgregarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPAgregarPersonajeLayout.createSequentialGroup()
                        .addComponent(jLFuerza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLAFisica))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFAFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLAMental)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFAMental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLPuntosVida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFPuntosVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jPBG.add(jPAgregarPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Personajes");
        jTPersonajes.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTPersonajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTPersonajesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTPersonajes);

        jLabel1.setText("Personajes Clasificados");

        jTFName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNameActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jTPPersonajeInfo);

        javax.swing.GroupLayout jPListadoLayout = new javax.swing.GroupLayout(jPListado);
        jPListado.setLayout(jPListadoLayout);
        jPListadoLayout.setHorizontalGroup(
            jPListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPListadoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(jPListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(jTFName))
                .addGap(80, 80, 80))
        );
        jPListadoLayout.setVerticalGroup(
            jPListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPListadoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPBG.add(jPListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPSimulacionLayout = new javax.swing.GroupLayout(jPSimulacion);
        jPSimulacion.setLayout(jPSimulacionLayout);
        jPSimulacionLayout.setHorizontalGroup(
            jPSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPSimulacionLayout.setVerticalGroup(
            jPSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPBG.add(jPSimulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAgregarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCBUniversoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBUniversoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBUniversoActionPerformed

    private void jTFPoderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPoderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPoderActionPerformed

    private void jTFFuerzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFFuerzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFFuerzaActionPerformed

    private void jTFAFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFAFisicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFAFisicaActionPerformed

    private void jTFAMentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFAMentalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFAMentalActionPerformed

    private void jBtnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAgregarMouseClicked
            // TODO add your handling code here:
            jPVacio.setVisible(false);
            jPListado.setVisible(false);
            jPAgregarPersonaje.setVisible(true);
    }//GEN-LAST:event_jBtnAgregarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String nombre, universo, fuerza, poder, aMental, aFisica, hp;
        nombre = jTFNombre.getText();
        universo = (String)jCBUniverso.getSelectedItem();
        fuerza = jTFFuerza.getText();
        poder = jTFPoder.getText();
        aMental = jTFAMental.getText();
        aFisica = jTFAFisica.getText();
        hp = jTFPuntosVida.getText();
        
        if ((String)jCBUniverso.getSelectedItem()=="Marvel") {
            personajes.add(new Marvel(nombre, universo, fuerza, poder, aMental, aFisica, hp));
        }else if((String)jCBUniverso.getSelectedItem()=="Capcom"){
            personajes.add(new Capcom(nombre, universo, fuerza, poder, aMental, aFisica, hp));
        }else if ((String)jCBUniverso.getSelectedItem()=="DC") {
            personajes.add(new DC(nombre, universo, fuerza, poder, aMental, aFisica, hp));
        }else{
            personajes.add(new MortalKombat(nombre, universo, fuerza, poder, aMental, aFisica, hp));
        }
        JOptionPane.showMessageDialog(this, "Agregado con exito");
        int pos = personajes.size();
        
        DefaultTreeModel modelo = (DefaultTreeModel)jTPersonajes.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode)modelo.getRoot();
        DefaultMutableTreeNode n
                        = new DefaultMutableTreeNode(universo);
                DefaultMutableTreeNode p
                        = new DefaultMutableTreeNode(personajes.get(pos-1));
                n.add(p);
                raiz.add(n);
                modelo.reload();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        jPAgregarPersonaje.setVisible(false);
        jPListado.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jTPersonajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTPersonajesMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            //seleccionar un nodo con click derecho
            int row = jTPersonajes.getClosestRowForLocation(
                    evt.getX(), evt.getY());
            jTPersonajes.setSelectionRow(row);
            Object v1
                    = jTPersonajes.getSelectionPath().
                    getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof Personaje) {
                personaje_seleccionada
                        = (Personaje) nodo_seleccionado.
                        getUserObject();
                String nombre, universo, fuerza, poder, aMental, aFisica, hp;
                nombre = personaje_seleccionada.getNombre();
                fuerza = personaje_seleccionada.getFuerza();
                poder = personaje_seleccionada.getPoder();
                aMental = personaje_seleccionada.getaMental();
                aFisica = personaje_seleccionada.getaFisica();
                hp = personaje_seleccionada.getHp();
                String t = "Poder -> "+poder+"\nFuerza -> "+fuerza+"\nAgilidad Mental -> "+aMental+"\nAgilidad Fisica -> "+aFisica+"\nPuntos de Vida -> "+hp;
                String s = nombre;
                jTPPersonajeInfo.setText(t);
                jTFName.setText(s);
            }else{
                
            }
            
        }
    }//GEN-LAST:event_jTPersonajesMouseClicked

    private void jTFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab5P2_LuisMontalvan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab5P2_LuisMontalvan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab5P2_LuisMontalvan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab5P2_LuisMontalvan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab5P2_LuisMontalvan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jCBUniverso;
    private javax.swing.JLabel jLAFisica;
    private javax.swing.JLabel jLAMental;
    private javax.swing.JLabel jLFuerza;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLPoder;
    private javax.swing.JLabel jLPuntosVida;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLUniverso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPAgregarPersonaje;
    private javax.swing.JPanel jPBG;
    private javax.swing.JPanel jPListado;
    private javax.swing.JPanel jPSimulacion;
    private javax.swing.JPanel jPVacio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTFAFisica;
    private javax.swing.JTextField jTFAMental;
    private javax.swing.JTextField jTFFuerza;
    private javax.swing.JTextField jTFName;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFPoder;
    private javax.swing.JTextField jTFPuntosVida;
    private javax.swing.JTextPane jTPPersonajeInfo;
    private javax.swing.JTree jTPersonajes;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    ArrayList<Personaje> personajes = new ArrayList();
    DefaultMutableTreeNode nodo_seleccionado;
    Personaje personaje_seleccionada;
}
